---
registry_token: "{{ vault_registry_token }}"

mqtt_host: "{{ vault_mqtt_host }}"
mqtt_port: "{{ vault_mqtt_port }}"
mqtt_user: noolite
mqtt_password: "{{ vault_mqtt_password }}"

switches:
  - channel: 0
    id: noolite_power_outlet_1
    name: noolite power outlet
    component: switch

  - channel: 2
    id: bathroom_fan
    name: bathroom fan
    component: fan

lights:
  - channel: 1
    id: noolite_light_1
    name: bedroom light

  - channel: 7
    id: noolite_hall_light
    name: hall light

  - channel: 8
    id: noolite_living_room_light
    name: living room light

binary_sensors:
  - channel: 5
    id: noolite_door
    name: door
    device_class: door

  - channel: 3
    id: noolite_bathroom_moisture
    name: bathroom moisture
    device_class: moisture

  - channel: 4
    id: noolite_washer_moisture
    name: washer moisture
    device_class: moisture

  - channel: 6
    id: noolite_dishwasher_moisture
    name: dishwasher moisture
    device_class: moisture
