---
registry_token: "{{ vault_registry_token }}"

mqtt_host: "{{ vault_mqtt_host }}"
mqtt_port: "{{ vault_mqtt_port }}"
mqtt_user: noolite
mqtt_password: "{{ vault_mqtt_password }}"

switches:
  - channel: 0
    id: noolite_power_outlet_1
    name: noolite power outlet

lights:
  - channel: 1
    id: noolite_light_1
    name: bedroom light

binary_sensors:
  - channel: 5
    id: noolite_door
    name: door
    device_class: door
