---
- name: deploy
  hosts: rasp
  gather_facts: no
  tasks:
    - name: login github docker registry
      docker_login:
        registry: docker.pkg.github.com
        username: dmnbars
        password: "{{ registry_token }}"

    - name: start noolite
      docker_container:
        name: "noolite"
        image: docker.pkg.github.com/dmnbars/noolite/noolite:latest
        state: started
        pull: yes
        restart_policy: always
        restart: yes
        devices:
          - "/dev/ttyUSB0:/dev/ttyUSB0"
        env:
          LOG_LEVEL: debug
          SERIAL_PORT: /dev/ttyUSB0
          MQTT_HOST: "{{ mqtt_host }}"
          MQTT_PORT: "{{ mqtt_port }}"
          MQTT_USERNAME: "{{ mqtt_user }}"
          MQTT_PASSWORD: "{{ mqtt_password }}"
          SWITCHES: "{{ switches|to_json }}"
          LIGHTS: "{{ lights|to_json }}"
