---
- name: prepare
  hosts: rasp
  tasks:
    - name: upgrade packages
      become: yes
      apt:
        update_cahe: yes
        upgrade: yes

    - name: install deps
      become: yes
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: install GPG key
      become: yes
      apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present

    - name: add apt repository
      become: yes
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present

    - name: install docker
      become: yes
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: docker permissions
      block:
        - set_fact:
            user: "{{ ansible_env['USER'] }}"

        - name: ensure group "docker" exists
          group:
            name: docker
            state: present

        - name: add currenct user to docker group
          become: yes
          user:
            name: "{{ ansible_env['USER'] }}"
            groups: docker
            append: yes

        - name: fix docker permissions
          become: yes
          file:
            path: "{{ ansible_env['HOME'] }}/.docker"
            recurse: true
            owner: "{{ ansible_env['USER'] }}"
            group: docker
